
package fr.eseo.jee.agence.velo.sw.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.1
 * Fri Mar 23 16:21:54 CET 2018
 * Generated source version: 3.2.1
 */

@XmlRootElement(name = "annulerVelo", namespace = "http://sw.velo.agence.jee.eseo.fr/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "annulerVelo", namespace = "http://sw.velo.agence.jee.eseo.fr/")

public class AnnulerVelo {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

