
package fr.eseo.jee.agence.velo.sw.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.1
 * Wed Mar 21 11:17:49 CET 2018
 * Generated source version: 3.2.1
 */

@XmlRootElement(name = "reservationVelo", namespace = "http://sw.velo.agence.jee.eseo.fr/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reservationVelo", namespace = "http://sw.velo.agence.jee.eseo.fr/")

public class ReservationVelo {

    @XmlElement(name = "arg0")
    private fr.eseo.jee.agence.velo.modele.ReservationVelo arg0;

    public fr.eseo.jee.agence.velo.modele.ReservationVelo getArg0() {
        return this.arg0;
    }

    public void setArg0(fr.eseo.jee.agence.velo.modele.ReservationVelo newArg0)  {
        this.arg0 = newArg0;
    }

}

