
package fr.eseo.jee.agence.velo.sw.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.1
 * Wed Mar 21 11:17:49 CET 2018
 * Generated source version: 3.2.1
 */

@XmlRootElement(name = "trouverVeloResponse", namespace = "http://sw.velo.agence.jee.eseo.fr/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trouverVeloResponse", namespace = "http://sw.velo.agence.jee.eseo.fr/")

public class TrouverVeloResponse {

    @XmlElement(name = "return")
    private java.util.List<fr.eseo.jee.agence.velo.modele.Velo> _return;

    public java.util.List<fr.eseo.jee.agence.velo.modele.Velo> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<fr.eseo.jee.agence.velo.modele.Velo> new_return)  {
        this._return = new_return;
    }

}

