
package fr.eseo.jee.agence.velo.sw.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.1
 * Thu Mar 29 17:04:02 CEST 2018
 * Generated source version: 3.2.1
 */

@XmlRootElement(name = "trouverVelo", namespace = "http://sw.velo.agence.jee.eseo.fr/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trouverVelo", namespace = "http://sw.velo.agence.jee.eseo.fr/")

public class TrouverVelo {

    @XmlElement(name = "arg0")
    private fr.eseo.jee.agence.velo.modele.Velo arg0;

    public fr.eseo.jee.agence.velo.modele.Velo getArg0() {
        return this.arg0;
    }

    public void setArg0(fr.eseo.jee.agence.velo.modele.Velo newArg0)  {
        this.arg0 = newArg0;
    }

}

